dist: trusty
sudo: false
group: beta
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - xdotool
  firefox: "49.0"
install: 
- echo $JAVA_HOME
- $JAVA_HOME/bin/java -version
- mvn compile test-compile --show-version --batch-mode
script: mvn verify -B
