dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - xdotool
    - chromium-browser
  firefox: "49.0"
before_install:
  - find /tmp -maxdepth 1 -iname ".X*"
install: echo "Intentionally doing nothing in the travis install step"
before_script:
  - find /tmp -maxdepth 1 -iname ".X*"
script: mvn install -B -Ptravis -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
