dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - xdotool
    - chromium-browser
  firefox: "49.0"
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: mvn compile test-compile
before_script:
  - find /tmp -maxdepth 1 -iname ".X*"
script: mvn install -B -Ptravis -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
