dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - imagemagick
    - xdotool
    - chromium-browser
  firefox: "49.0"
before_install:
  - dpkg-query -l xvfb
  - ps u --pid $(pgrep Xvfb)
  - find /tmp -maxdepth 1 -iname ".X*"
install: mvn compile test-compile
before_script:
  - find /tmp -maxdepth 1 -iname ".X*"
script: mvn install -B -Ptravis -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
