dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - xdotool
    - chromium-browser
  firefox: "49.0"
script: mvn verify -B -DAssumptions.fatal=true -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
