version: 0.16.{build}
image: Visual Studio 2017
skip_commits:
  message: "[skip appveyor]"
build_script:
- cmd: >-
    echo "JAVA_HOME=%JAVA_HOME%"

    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    java -version

    mvn --version

    mvn install --quiet --batch-mode
